### ISSUE TITLE
Atualização na verificação de postback

### ISSUE THREAD

**Issue by luiseduardobraschi** [marcosgomesneto/woocommerce-pagarme-pix-payment#11]
Olá. Recebemos um e-mail da Pagar.me sobre essa atualização da verificação do postback. Fiz a mudança no meu fork do plug-in do Cláudio Sanches e neste e confirmo que funciona.

![image](https://github.com/marcosgomesneto/woocommerce-pagarme-pix-payment/assets/700448/1a4339ad-d79a-4697-a2ad-aa1e46b4a85f)

Segue o link da documenta:
https://docs.pagar.me/v4/reference/validando-um-postback

**Comment by marcosgomesneto** [comment]
Estou fazendo o update dessa inssue

**Comment by luiseduardobraschi** [comment]
@marcosgomesneto Não cheguei a testar ainda, mas não deveria pegar os valores por `file_get_contents('php://input');`?

https://github.com/marcosgomesneto/woocommerce-pagarme-pix-payment/blob/8d77574ea580a4d89508b39cf1399a0dedf025d6/src/Pagarme/PagarmeApiV4.php#L242

Meu Gist que tá funcionando:

https://gist.github.com/luiseduardobraschi/f66145a03a5276fc4bdc823abe2e96e4#file-functions-php-L14
